export * from './HomePage'
export * from './LoginPage'
export * from './WatchPage'
export * from './ProfilePage'
export * from './MoviesPage'
export * from './SeriesPage'
export * from './SearchPage'
export * from './TitlePage'
